# Generated by Django 5.1.5 on 2025-01-16 20:20

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montadora',
            name='ano_fundacao',
            field=models.IntegerField(verbose_name='Ano de Fundação'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField(validators=[core.models.validate_ano_lancamento], verbose_name='Ano de Lançamento')),
                ('preco_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modelos', to='core.montadora')),
            ],
        ),
    ]
