# Generated by Django 5.1.5 on 2025-01-16 15:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Montadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('ano_fundacao', models.IntegerField(validators=[core.models.validate_ano_fundacao])),
            ],
        ),
    ]
