# Generated by Django 5.1.5 on 2025-01-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('motorizacao', models.CharField(choices=[('1.0', 'Motor 1.0'), ('1.4', 'Motor 1.4'), ('1.6', 'Motor 1.6'), ('2.0', 'Motor 2.0')], max_length=3)),
                ('tipo_cambio', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=10)),
                ('em_producao', models.BooleanField(default=True)),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modelos', to='core.montadora')),
            ],
        ),
    ]
